baseURL = "https://bramvanginneken.org/"
languageCode = "en-us"
title = "Bram van Ginneken"
theme = "gokarna"

[params]
  avatarURL = "/images/avatar.jpg"  # Add your avatar in static/images/
  ShowToc = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  customCSS = [ "css/custom.css" ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3